version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: udemy
            MYSQL_USER: sami
            MYSQL_PASSWORD: password
        restart: always
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
